baseURL = "https://ja.mhatta.org/"
title = "Masayuki Hatta a.k.a. mhatta"
author = "Masayuki Hatta"
languageCode = "ja"
DefaultContentLanguage = "ja"
enableInlineShortcodes = true
theme = "Blonde"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
googleAnalytics = "UA-938391-2"

# Disqus Comment System
disqusShortname = "jamhattaorg"

[markup.goldmark.renderer]
  unsafe = true

[permalinks]
  post = "/blog/:year/:month/:day/:slug/"

[params]
# The number of articles to be displayed on a single page.
paginator_pages = "5"

# Enable this if you want the archive list to be in a drop-down format.
archive_dropdown = "true"

# Number of tags to be displayed.
tagsLimit = 20

  [params.post]
    # See the Tailwind CSS documentation to set it up.
    # Recommended settings are h-32 to h-48.
    # https://tailwindcss.com/docs/height
    thumbnail_height = "h-48"

    # https://tailwindcss.com/docs/width
    thumbnail_width = "w-auto"

  [params.widgets]
    archives = false
    categories = true
    tags = true
    recentposts = true
    search = true

# If you're using Yandex.Metrica, you can enable this feature.
[params.analytics.yandexmetrica]
    enabled = true
    tagNumber = '73933261'

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 3

  [[menu.main]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com/mhatta"
    weight = 4

  [[menu.main]]
    identifier = "linkedin"
    name = "LinkedIn"
    url = "https://linkedin.com/in/mhatta/"
    weight = 5

  [[menu.main]]
    identifier = "instagram"
    name = "Instagram"
    url = "https://instagram.com/masayukihatta"
    weight = 6

[taxonomies]
category = "categories"
tag = "tags"
archive = "archives"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

[build]
  writeStats = true
